### ISSUE TITLE
Unit tests need their own source set

### ISSUE THREAD

**Issue by mattbdean** [euparkeria/RedditJerk#2]
Maven projects use different source sets to differentiate between different parts of the project. By default, the main code goes in `main` and the unit tests go in `test`:

```
src/
    main/
        java/
            ga.dryco.redditjerk/  <-- main project files
    test/
        java/
            ga.dryco.redditjerk/  <-- unit tests
```

See [here](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html) for more.

**Comment by euparkeria** [comment]
Thanks, I moved the directory, though I am yet to write real unit tests :)

**Comment by mattbdean** [comment]
I'd recommend using TestNG or JUnit, both great frameworks with enormous user bases.
